# Generated by Django 3.0.7 on 2020-06-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactMail', models.TextField(default='admin@localhost', verbose_name='Contact Mail')),
                ('noIndex', models.BooleanField(default=False, verbose_name='No Index')),
            ],
            options={
                'db_table': 'settings',
            },
        ),
    ]
