# Generated by Django 3.0.7 on 2020-06-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='bannerImageUrl',
            field=models.TextField(default='https://picsum.photos/200/400/?blur=2', verbose_name='Banner Image URL'),
        ),
        migrations.AddField(
            model_name='setting',
            name='mainText',
            field=models.TextField(default='You are reading the main text', verbose_name='Main Text'),
        ),
    ]
