# Generated by Django 3.0.7 on 2020-06-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingsApp', '0002_auto_20200618_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='metaDesc',
            field=models.TextField(blank='', default='', verbose_name='Meta Desc'),
        ),
        migrations.AddField(
            model_name='setting',
            name='metaTags',
            field=models.TextField(blank='', default='', verbose_name='Meta Tags'),
        ),
        migrations.AddField(
            model_name='setting',
            name='tracker',
            field=models.TextField(blank='', default='', verbose_name='Tracker Code'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='mainText',
            field=models.TextField(blank='', default='You are reading the main text', verbose_name='Main Text'),
        ),
    ]
